apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: evl9uozj9-go 
  janus-idp.io/tekton: evl9uozj9-go
  backstage.io/kubernetes-id: evl9uozj9-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: evl9uozj9-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  